### ISSUE TITLE
New Video: Handmade Hero Day 121 - Rendering in Tiles (Marathon)

### ISSUE THREAD

**Issue by dspecht** [HandmadeCompanion/HandmadeCompanion#118]
place holder because Miblo is working on it

**Comment by miblodelcarpio** [comment]
Done. Just need to succinctly describe what happens between 02:30:56–02:36:34.

    02:30:56 - Introduce ExpandRectangleToIncludePoint
    02:30:56 - TODO(matt): WHAT IS HAPPENING HERE?!
    Take each individual point of the 4 corners of our potentially rotated quad
    that we're texture mapping, and it's trying to make sure that it gets the min /
    max bounds of those

**Comment by dspecht** [comment]
Miblo finished this and the PR was https://github.com/HandmadeCompanion/HandmadeCompanion/pull/119

**Comment by ajohnson23** [comment]
Thanks @miblodelcarpio and @dspecht ! I started watching this one and I noticed a few interesting points that weren't annotated, so I hope you don't mind if I beef up a few bits up later this week.

**Comment by miblodelcarpio** [comment]
Please go for it, @ajohnson23! This was my first one, so I'm bound to have missed all sorts of good stuff.

**Comment by abnercoimbre** [comment]
It's a 4-hour video so we will reopen this issue for one more revision.

**Comment by dspecht** [comment]
this still being looked at?

**Comment by ajohnson23** [comment]
Yep, just haven't had time this week.

**Comment by miblodelcarpio** [comment]
Hi @ajohnson23, I'm just about to bunny-hop this issue in my quest to catch up to the present day. Are you still keen to beef it up?

**Comment by Kelimion** [comment]
Is this issue still an issue, or was it left open undecided?

**Comment by ZedZull** [comment]
Seems complete per issue #119
