### ISSUE TITLE
New Video: Handmade Hero Day 115 - SIMD Basics

### ISSUE THREAD

**Issue by abnercoimbre** [HandmadeCompanion/HandmadeCompanion#122]
Needs annotating.

**Comment by miblodelcarpio** [comment]
Yo @effect0r, are you still keen to do #122, #123, #124 and #125? Once I've done #121 I'll leapfrog over these ones if you still want them.

**Comment by effect0r** [comment]
Yeah man I'll get them when I'm back from the beach

**Comment by miblodelcarpio** [comment]
Alright, cool. Leapfrogging it is.

**Comment by ZedZull** [comment]
Reopening for Q: attribution

**Comment by ZedZull** [comment]
Oops, this one's already done.
