### ISSUE TITLE
Episode guide index page hasn't been updated since Week 15

### ISSUE THREAD

**Issue by ajohnson23** [HandmadeCompanion/HandmadeCompanion#126]
@abnercoimbre @mvandevander and @dspecht are already aware of this issue, but I'm putting it here for tracking purposes -- The Episode guide index page at https://forums.handmadehero.org/jace/guide/ hasn't been updated since week 15. I believe Abner and Matthew have tried to reach out to @bnwasteland to ask if the auto-update mechanism can be fixed to get it working again, but they haven't heard back yet.

Please update this when there's any new word on this. Thanks!

**Comment by dspecht** [comment]
https://github.com/HandmadeCompanion/HandmadeCompanion/commit/a9cc959d7208a378d4f7a9577c79cdafc7537579    

Also another week to ensure the file had been pushed properly had a glitch on my end so had to make sure.

**Comment by abnercoimbre** [comment]
Fixed.
