### ISSUE TITLE
Status designations on episode guide index page

### ISSUE THREAD

**Issue by ajohnson23** [HandmadeCompanion/HandmadeCompanion#127]
It'd be nice if there were a status next to each episode on the episode guide index page, such as
"[Annotations Complete]", "[Annotations Incomplete]", etc, just so folks that visit the page can quickly know which videos actually have annotations -- currently, a ton of them don't have annotations, so it's a bit of a tease to click on them and discover an empty page with a video on it.
I can look into this once #126 is sorted out.

**Comment by miblodelcarpio** [comment]
I think this is a potentially nice idea, although maybe it'd be better just to mark the incomplete annotations to save cluttering up the page too much.

**Comment by ajohnson23** [comment]
Yup, that works too. Maybe "[No Annotations]" and "[Q&A Annotations Only]" since we have a number of episodes where only the Q&A was annotated.

**Comment by miblodelcarpio** [comment]
That sounds good. It's got my vote.

**Comment by abnercoimbre** [comment]
Yea I'm taking care of those episodes that only have annotated Q&A or time stamps with no Q&A. The [complete/incomplete] status is a good idea. Greenlit.

**Comment by dspecht** [comment]
Since we have some episodes that have notes , maybe we can just say [incomplete] if no annotations/timestamps are done. with [notes only] if for some reason we don't have the annotations but we have notes. and [with notes]  for the ones that have notes ?

**Comment by ajohnson23** [comment]
Settled on just having a "Annotations incomplete" next to any episodes that don't have annotation of any kind -
https://forums.handmadehero.org/jace/guide/

This was straightforward to implement, since we can just check for the presence of markers on the dayxxx.html.md files during generation of the table of contents. No additional manual curating of data is needed.

Note, it can't tell if a video has only Q&A annotations, for example... it considers that "complete". We should just fix those by adding full annotations as soon as possible :)

**Comment by ajohnson23** [comment]
Also added (With Notes) per Dustin's idea.
