### ISSUE TITLE
New Video: Handmade Hero Day 122 - Introduction to Multithreading

### ISSUE THREAD

**Issue by miblodelcarpio** [HandmadeCompanion/HandmadeCompanion#128]
Needs annotating: https://www.youtube.com/watch?v=qkugPXGeX58

**Comment by abnercoimbre** [comment]
Thank you for adding this issue.

**Comment by ZedZull** [comment]
Reopening for Q: attribution

**Comment by ZedZull** [comment]
Oops, this one's already done.
