### ISSUE TITLE
New Video: Handmade Hero Day 123 - Interlocked Operations

### ISSUE THREAD

**Issue by dspecht** [HandmadeCompanion/HandmadeCompanion#129]
base file -https://github.com/HandmadeCompanion/HandmadeCompanion/commit/e4de2f527daac835e13ddb329e9b7bc33bbcbe2b
needs annotations

**Comment by ZedZull** [comment]
Reopening for Q: attribution

**Comment by ZedZull** [comment]
Oops, this one's already done.
