### ISSUE TITLE
New Video: Handmade Hero  Day 126 - Circular FIFO Work Queue

### ISSUE THREAD

**Issue by dspecht** [HandmadeCompanion/HandmadeCompanion#132]
https://github.com/HandmadeCompanion/HandmadeCompanion/commit/074e14249e9ade4fbe655366f8432ae2fe9dd56d -base file added

**Comment by Chronister** [comment]
Done and pushed.

**Comment by debiatan** [comment]
The annotation parser requires a space after the colon that separates timestamps and annotations. Travis logged the problem but it exited without notifying it: 

https://travis-ci.org/HandmadeCompanion/HandmadeCompanion/builds/76723225

I've already added those extra spaces, but I've forgotten to mention the issue number in my commit:
https://github.com/HandmadeCompanion/HandmadeCompanion/commit/0c25c514a1b257eca402011844dcf9b8979f5465

**Comment by ZedZull** [comment]
Reopening for Q: attribution
