### ISSUE TITLE
New Video: Handmade Hero Day 131 - Asynchronous Ground Chunk Composition

### ISSUE THREAD

**Issue by miblodelcarpio** [HandmadeCompanion/HandmadeCompanion#137]
Needs annotating: https://www.youtube.com/watch?v=6blXhvPIz5g

**Comment by debiatan** [comment]
Sorry for the wrong reference. I don't know why I assumed issues and days would share the same id.

**Comment by ZedZull** [comment]
Reopening for Q: attribution

**Comment by ZedZull** [comment]
Oops, this one's already done.
