### ISSUE TITLE
New Video: Handmade Hero Day 132 - Asset Streaming

### ISSUE THREAD

**Issue by miblodelcarpio** [HandmadeCompanion/HandmadeCompanion#138]
Needs annotating: https://www.youtube.com/watch?v=qyHM36RQxAI

**Comment by debiatan** [comment]
Sorry for the wrong reference. I don't know why I assumed issues and days would share the same id.

**Comment by ZedZull** [comment]
Reopening for Q: attribution

**Comment by ZedZull** [comment]
Oops, this one's already done.
