### ISSUE TITLE
New Video: Handmade Hero Day 141 - Streaming Large Audio in Chunks

### ISSUE THREAD

**Issue by miblodelcarpio** [HandmadeCompanion/HandmadeCompanion#147]
Needs annotating: https://www.youtube.com/watch?v=Yvv9nVqGC5w

**Comment by miblodelcarpio** [comment]
@debiatan Nice work with this. I'm closing the issue, assuming that you're satisfied it's done.

Something that'll be helpful is if you remember to assign yourself to the issue you're working on, just on the off-chance that another Pusher comes along intending to work on it. You'll find the "assign yourself" link on the right hand side of the page. Also, in your commit message you can include the issue number by doing, e.g. [#42]. This just helps to keep a timeline of the commits associated with the issue. And then, once you're done, feel free to close the issue. No need to wait for the person who opened it to close it.

**Comment by debiatan** [comment]
Got it. Thanks for explaining!

**Comment by ZedZull** [comment]
Reopening for Q: attribution
