### ISSUE TITLE
New Video: Handmade Hero Day 025 - Finishing the Win32 Prototyping Layer

### ISSUE THREAD

**Issue by bnwasteland** [HandmadeCompanion/HandmadeCompanion#20]
Handmade Hero Day 025 - Finishing the Win32 Prototyping Layer<br>
http://ift.tt/1zJJRRH<br><div style="color: #000000; font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-size: 12px; width: 555px;">
<table cellspacing="0" cellpadding="0" border="0"><tbody>
<tr>
<td width="140" valign="top" rowspan="2">
<div style="margin: 0px 10px 5px 0px;"><a href="http://ift.tt/1zJJRRH"><img alt="" src="http://ift.tt/1Hcmssn"></a></div>
</td>
<td width="256" valign="top">
<div style="font-size: 12px; font-weight: bold;">
<a style="font-size: 15px; font-weight: bold;" href="http://ift.tt/1zJJRRH">Handmade Hero Day 025 - Finishing the Win32 Prototyping Layer</a><br>
</div>
<div style="font-size: 12px; margin: 3px 0px;"><span>Day 025 of coding on Handmade Hero. See http://handmadehero.org for details.</span></div>
</td>
<td style="font-size: 11px; line-height: 1.4em; padding-left: 20px; padding-top: 1px;" width="146" valign="top">
<div>
<span style="color: #666666; font-size: 11px;">From:</span> <a href="http://ift.tt/13k8nMC">Handmade Hero</a>
</div>
<div>
<span style="color: #666666; font-size: 11px;">Views:</span> 0</div>
<div style="white-space: nowrap; text-align: left;">
<img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS">
</div>
<div style="font-size: 11px;">0 <span style="color: #666666; font-size: 11px;">ratings</span>
</div>
</td>
</tr>
<tr>
<td>
<span style="color: #666666; font-size: 11px;">Time:</span> <span style="color: #000000; font-size: 11px; font-weight: bold;">02:30:18</span>
</td>
<td style="font-size: 11px; padding-left: 20px;">
<span style="color: #666666; font-size: 11px;">More in</span> <a href="http://ift.tt/tGpe6o">Education</a>
</td>
</tr>
</tbody></table>
</div>
<br><br>
via Uploads by Handmade Hero http://ift.tt/1zFBcjl<br>
December 19, 2014 at 06:34PM

**Comment by theinternetftw** [comment]
Complete.
