### ISSUE TITLE
Days 26-28 were in the wrong folder for a while

### ISSUE THREAD

**Issue by theinternetftw** [HandmadeCompanion/HandmadeCompanion#27]
Days 26-28 aren't in win32 land, but they've been pushed live in the win32 folder for a while.

Currently, I've moved them to a new folder (game-architecture), but left copies in the old one to not break public urls.

Options:

* That's good enough, leave it like that.

* Break the urls, delete the files.

* Fix it sever side with 301s

* Fix it docpad-side with something like https://github.com/docpad/docpad-plugin-cleanurls

**Comment by dspecht** [comment]
Closed Please reopen if you feel this has not been solved be and @abnercoimbre are trying to get this place caught up and cleaned up.
