### ISSUE TITLE
 New Video: Handmade Hero Day 247 - Simplifying Debug Values

### ISSUE THREAD

**Issue by ffsjs** [HandmadeCompanion/HandmadeCompanion#272]
Q&A already done.
Needs annotating: https://www.youtube.com/watch?v=JqcphfRybd4
https://hero.handmadedev.org/videos/game-architecture/day247.html

**Comment by ffsjs** [comment]
yaaay, happy to close my first issue :)

**Comment by miblodelcarpio** [comment]
@ffsjs Added the stub with commits ed0ce2e9de6ebc2d23d7951daf010a26414c7eb2, 5ed8c6c533c4554406e4c080cf70aae7edb09fad and 806dd7dc286f8740e84bc504b0b3546d661a05c7, and the full annotations with commits 119133ed8f52aaba96d0ccccffca8cf44a916fde, 37ed475e019b599c1f024d340f65cf676baff3a0 and f35795dd46ca9238ce6f8d5c24c1c2e9d6ddbb9f.
