### ISSUE TITLE
New Video: Handmade Hero Day 248 - Cleaning Up Data Block Display

### ISSUE THREAD

**Issue by ffsjs** [HandmadeCompanion/HandmadeCompanion#273]
Q&A done.
Needs annotating: https://www.youtube.com/watch?v=Thr10pFx984
https://hero.handmadedev.org/videos/game-architecture/day248.html

**Comment by miblodelcarpio** [comment]
@ffsjs added the stub with commits 5a7ea7270e6194d239274e9fdf49e24c18295258 and 8789f80334230917c4abea91dd2cd62b0a60c887
