### ISSUE TITLE
New Video: Handmade Hero Day 249 - Cleaning Up Debug Macros

### ISSUE THREAD

**Issue by ffsjs** [HandmadeCompanion/HandmadeCompanion#274]
1 Q&A done. Just one. That's how it happenned.
 Needs annotating: https://www.youtube.com/watch?v=NVnlQ7KMGa8
 https://hero.handmadedev.org/videos/game-architecture/day249.html

**Comment by miblodelcarpio** [comment]
@ffsjs added the stub with commit 6a65ec61356ac632512c862f3b6fd81c8dbcfc5f
