### ISSUE TITLE
New Video: Handmade Hero Day 063 - Simulation Regions

### ISSUE THREAD

**Issue by bnwasteland** [HandmadeCompanion/HandmadeCompanion#62]
Handmade Hero Day 063 - Simulation Regions<br>
http://ift.tt/1AejeqE<br><div style="color: #000000; font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-size: 12px; width: 555px;">
<table cellspacing="0" cellpadding="0" border="0"><tbody>
<tr>
<td width="140" valign="top" rowspan="2">
<div style="margin: 0px 10px 5px 0px;"><a href="http://ift.tt/1AejeqE"><img alt="" src="http://ift.tt/1EdJwGK"></a></div>
</td>
<td width="256" valign="top">
<div style="font-size: 12px; font-weight: bold;">
<a style="font-size: 15px; font-weight: bold;" href="http://ift.tt/1AejeqE">Handmade Hero Day 063 - Simulation Regions</a><br>
</div>
<div style="font-size: 12px; margin: 3px 0px;"><span>Day 063 of coding on Handmade Hero. See http://handmadehero.org for details.</span></div>
</td>
<td style="font-size: 11px; line-height: 1.4em; padding-left: 20px; padding-top: 1px;" width="146" valign="top">
<div>
<span style="color: #666666; font-size: 11px;">From:</span> <a href="http://ift.tt/13k8nMC">Handmade Hero</a>
</div>
<div>
<span style="color: #666666; font-size: 11px;">Views:</span> 0</div>
<div style="white-space: nowrap; text-align: left;">
<img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS"><img style="margin: 0px; padding: 0px; vertical-align: middle; font-size: 11px;" align="top" alt="" src="http://ift.tt/iBDJTS">
</div>
<div style="font-size: 11px;">0 <span style="color: #666666; font-size: 11px;">ratings</span>
</div>
</td>
</tr>
<tr>
<td>
<span style="color: #666666; font-size: 11px;">Time:</span> <span style="color: #000000; font-size: 11px; font-weight: bold;">01:29:10</span>
</td>
<td style="font-size: 11px; padding-left: 20px;">
<span style="color: #666666; font-size: 11px;">More in</span> <a href="http://ift.tt/tGpe6o">Education</a>
</td>
</tr>
</tbody></table>
</div>
<br><br>
via Uploads by Handmade Hero http://ift.tt/1zFBcjl<br>
February 12, 2015 at 03:16AM

**Comment by jpike** [comment]
Going to start on these annotations.

**Comment by miblodelcarpio** [comment]
Beautiful. Welcome aboard, @jpike! If you're unsure about anything and have access to the chat – either via [Twitch](http://twitch.tv/handmade_hero) or an IRC client – you'll find us in there.

**Comment by sir-pinecone** [comment]
@miblodelcarpio Here are some annotation updates

1:01:43 - handmade_sim_region.cpp: TODO(casey): Check a second rectangle to set the entity to be "movable" or not!
1:03:32 - Add a todo_check.bat script that lists out all the TODOs in the source files
1:07:10 - handmade.h: TODO(casey): Generation index so we know how "up to date" this entity is
1:07:27 - Continue answering previous question
1:24:34 - Wrap it up
